on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v2
      with:
         path: './src/github.com/kevinburke/semaphore'
    # staticcheck needs this for GOPATH
    - run: echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - run: echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - run: echo "GO111MODULE=off" >> $GITHUB_ENV
    - name: Run tests
      run: make ci
      working-directory: './src/github.com/kevinburke/semaphore'
